[package]
name = "vacs-data-validator"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
console = { workspace = true }
vacs-data-diagnostics = { workspace = true }
vacs-vatsim = { workspace = true }
