[[stations]]
id = "EPWW_FMP"
controlled_by = ["EPWW_FMP"]

[[stations]]
id = "EPWWB_HIGH"
controlled_by = [
  "EPWW_N_CTR",
  "EPWW_ALH_CTR",
  "EPWW_DBT_CTR",
  "EPWW_DBF_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWB_MID"
controlled_by = [
  "EPWW_DBT_CTR",
  "EPWW_DBF_CTR",
  "EPWW_N_CTR",
  "EPWW_ALH_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWB_LOW"
controlled_by = [
  "EPWW_DBT_CTR",
  "EPWW_DBF_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWWC_HIGH"
controlled_by = [
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALH_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_C_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWC_MID"
controlled_by = [
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALH_CTR",
  "EPWW_C_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWC_LOW"
controlled_by = [
  "EPWW_C_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWWD_HIGH"
controlled_by = [
  "EPWW_DTC_CTR",
  "EPWW_N_CTR",
  "EPWW_ALH_CTR",
  "EPWW_DBT_CTR",
  "EPWW_DT_CTR",
  "EPWW_DBF_CTR",
  "EPWW_D_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWD_MID"
controlled_by = [
  "EPWW_DBT_CTR",
  "EPWW_DT_CTR",
  "EPWW_DTC_CTR",
  "EPWW_DBF_CTR",
  "EPWW_N_CTR",
  "EPWW_ALH_CTR",
  "EPWW_D_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWD_LOW"
controlled_by = [
  "EPWW_D_CTR",
  "EPWW_DBT_CTR",
  "EPWW_DT_CTR",
  "EPWW_DTC_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWWE_HIGH"
controlled_by = [
  "EPWW_NE_CTR",
  "EPWW_E_CTR",
  "EPWW_S_CTR",
  "EPWW_N_CTR",
  "EPWW_ALH_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWE_MID"
controlled_by = [
  "EPWW_NE_CTR",
  "EPWW_E_CTR",
  "EPWW_S_CTR",
  "EPWW_N_CTR",
  "EPWW_ALH_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWE_LOW"
controlled_by = [
  "EPWW_NE_CTR",
  "EPWW_E_CTR",
  "EPWW_S_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWWF_HIGH"
controlled_by = [
  "EPWW_N_CTR",
  "EPWW_ALH_CTR",
  "EPWW_FG_CTR",
  "EPWW_DBF_CTR",
  "EPWW_F_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWF_MID"
controlled_by = [
  "EPWW_FG_CTR",
  "EPWW_DBF_CTR",
  "EPWW_N_CTR",
  "EPWW_ALH_CTR",
  "EPWW_F_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWF_LOW"
controlled_by = [
  "EPWW_F_CTR",
  "EPWW_FG_CTR",
  "EPWW_DBF_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWWG_HIGH"
controlled_by = [
  "EPWW_N_CTR",
  "EPWW_ALH_CTR",
  "EPWW_FG_CTR",
  "EPWW_DBF_CTR",
  "EPWW_G_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWG_MID"
controlled_by = [
  "EPWW_FG_CTR",
  "EPWW_N_CTR",
  "EPWW_DBF_CTR",
  "EPWW_ALH_CTR",
  "EPWW_G_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWG_LOW"
controlled_by = [
  "EPWW_G_CTR",
  "EPWW_FG_CTR",
  "EPWW_N_CTR",
  "EPWW_DBF_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWWJ_HIGH"
controlled_by = [
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_ALH_CTR",
  "EPWW_JR_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_J_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWJ_MID"
controlled_by = [
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALH_CTR",
  "EPWW_J_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWJ_LOW"
controlled_by = [
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWWN_HIGH"
controlled_by = [
  "EPWW_NE_CTR",
  "EPWW_N_CTR",
  "EPWW_E_CTR",
  "EPWW_ALH_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWN_MID"
controlled_by = [
  "EPWW_NE_CTR",
  "EPWW_N_CTR",
  "EPWW_E_CTR",
  "EPWW_ALH_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWN_LOW"
controlled_by = [
  "EPWW_NE_CTR",
  "EPWW_N_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWWR_HIGH"
controlled_by = [
  "EPWW_E_CTR",
  "EPWW_S_CTR",
  "EPWW_ALH_CTR",
  "EPWW_JR_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWR_MID"
controlled_by = [
  "EPWW_JR_CTR",
  "EPWW_E_CTR",
  "EPWW_S_CTR",
  "EPWW_ALH_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWR_LOW"
controlled_by = [
  "EPWW_JR_CTR",
  "EPWW_E_CTR",
  "EPWW_S_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWWT_HIGH"
controlled_by = [
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_ALH_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DT_CTR",
  "EPWW_TM_CTR",
  "EPWW_DBT_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWT_MID"
controlled_by = [
  "EPWW_TM_CTR",
  "EPWW_DT_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_DBT_CTR",
  "EPWW_S_CTR",
  "EPWW_ALH_CTR",
  "EPWW_ALL_CTR",
]

[[stations]]
id = "EPWWT_LOW"
controlled_by = [
  "EPWW_TM_CTR",
  "EPWW_DT_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_DBT_CTR",
  "EPWW_S_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWW_C"
controlled_by = ["EPWW_C_CTR"]

[[stations]]
id = "EPWW_D"
controlled_by = ["EPWW_D_CTR"]

[[stations]]
id = "EPWW_DBT"
controlled_by = ["EPWW_DBT_CTR"]

[[stations]]
id = "EPWW_DBF"
controlled_by = ["EPWW_DBF_CTR"]

[[stations]]
id = "EPWW_DT"
controlled_by = ["EPWW_DT_CTR"]

[[stations]]
id = "EPWW_DTC"
controlled_by = ["EPWW_DTC_CTR"]

[[stations]]
id = "EPWW_F"
controlled_by = ["EPWW_F_CTR"]

[[stations]]
id = "EPWW_FG"
controlled_by = ["EPWW_FG_CTR"]

[[stations]]
id = "EPWW_G"
controlled_by = ["EPWW_G_CTR"]

[[stations]]
id = "EPWW_J"
controlled_by = ["EPWW_J_CTR"]

[[stations]]
id = "EPWW_JR"
controlled_by = ["EPWW_JR_CTR"]

[[stations]]
id = "EPWW_NE"
controlled_by = ["EPWW_NE_CTR"]

[[stations]]
id = "EPWW_TM"
controlled_by = ["EPWW_TM_CTR"]

[[stations]]
id = "EPWW_TCJ"
controlled_by = ["EPWW_TCJ_CTR"]

[[stations]]
id = "EPWW_ALH"
controlled_by = ["EPWW_ALH_CTR"]

[[stations]]
id = "EPWW_ALL"
controlled_by = ["EPWW_ALL_CTR"]

[[stations]]
id = "EPWW_E"
controlled_by = ["EPWW_E_CTR"]

[[stations]]
id = "EPWW_N"
controlled_by = ["EPWW_N_CTR"]

[[stations]]
id = "EPWW_S"
controlled_by = ["EPWW_S_CTR"]

[[stations]]
id = "EPBA"
controlled_by = ["EPBA_R_TWR", "EPKK_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPBC"
controlled_by = ["EPBC_I_TWR", "EPWA_I_APP", "EPSY_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPBK"
controlled_by = ["EPBK_R_TWR", "EPSY_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPBY_TWR"
controlled_by = [
  "EPBY_TWR",
  "EPGD_APP",
  "EPWW_G_CTR",
  "EPWW_FG_CTR",
  "EPWW_N_CTR",
  "EPWW_DBF_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPBY_TMA"
controlled_by = [
  "EPBY_TWR",
  "EPGD_APP",
  "EPWW_G_CTR",
  "EPWW_FG_CTR",
  "EPWW_N_CTR",
  "EPWW_DBF_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPDE_MCTR"
controlled_by = ["EPDE_TWR", "EPDE_APP"]

[[stations]]
id = "EPDE_MTMA"
controlled_by = ["EPDE_APP"]

[[stations]]
id = "EPGD_GND"
controlled_by = [
  "EPGD_GND",
  "EPGD_TWR",
  "EPGD_L_APP",
  "EPGD_APP",
  "EPWW_G_CTR",
  "EPWW_FG_CTR",
  "EPWW_N_CTR",
  "EPWW_DBF_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPGD_TWR"
controlled_by = [
  "EPGD_TWR",
  "EPGD_L_APP",
  "EPGD_APP",
  "EPWW_G_CTR",
  "EPWW_FG_CTR",
  "EPWW_N_CTR",
  "EPWW_DBF_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPGD_LTMA"
controlled_by = [
  "EPGD_L_APP",
  "EPGD_APP",
  "EPWW_G_CTR",
  "EPWW_FG_CTR",
  "EPWW_N_CTR",
  "EPWW_DBF_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPGD_UTMA"
controlled_by = [
  "EPGD_APP",
  "EPWW_G_CTR",
  "EPWW_FG_CTR",
  "EPWW_N_CTR",
  "EPWW_DBF_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPGD_FIS"
controlled_by = ["EPGD_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPGL"
controlled_by = ["EPGL_R_TWR", "EPKK_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPGY"
controlled_by = ["EPGY_R_TWR", "EPSY_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPJA"
controlled_by = ["EPJA_R_TWR", "EPGD_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPKA"
controlled_by = ["EPKA_R_TWR", "EPKK_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPKK_DEL"
controlled_by = [
  "EPKK_DEL",
  "EPKK_GND",
  "EPKK_TWR",
  "EPKK_KK_APP",
  "EPKK_APP",
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPKK_GND"
controlled_by = [
  "EPKK_GND",
  "EPKK_TWR",
  "EPKK_KK_APP",
  "EPKK_APP",
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPKK_TWR"
controlled_by = [
  "EPKK_TWR",
  "EPKK_KK_APP",
  "EPKK_APP",
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPKK_TMA_E"
controlled_by = [
  "EPKK_E_APP",
  "EPKK_APP",
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPKK_DIR"
controlled_by = [
  "EPKK_KK_APP",
  "EPKK_E_APP",
  "EPKK_APP",
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPKT_DIR"
controlled_by = [
  "EPKK_KT_APP",
  "EPKK_E_APP",
  "EPKK_APP",
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPKK_TMA_W"
controlled_by = [
  "EPKK_APP",
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPKK_FIS"
controlled_by = ["EPKK_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPKI"
controlled_by = ["EPKI_R_TWR", "EPSY_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPKM"
controlled_by = ["EPKM_R_TWR", "EPKK_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPKP"
controlled_by = ["EPKP_R_TWR", "EPKK_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPKR"
controlled_by = ["EPKR_R_TWR", "EPKK_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPKS"
controlled_by = ["EPKS_TWR"]

[[stations]]
id = "EPKT_DEL"
controlled_by = [
  "EPKT_DEL",
  "EPKT_GND",
  "EPKT_TWR",
  "EPKK_APP",
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPKT_GND"
controlled_by = [
  "EPKT_GND",
  "EPKT_TWR",
  "EPKK_APP",
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPKT_TWR"
controlled_by = [
  "EPKT_TWR",
  "EPKK_APP",
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPLB_TWR"
controlled_by = [
  "EPLB_TWR",
  "EPWW_JR_CTR",
  "EPWW_E_CTR",
  "EPWW_S_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPLB_TMA"
controlled_by = [
  "EPLB_TWR",
  "EPWW_JR_CTR",
  "EPWW_E_CTR",
  "EPWW_S_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPLL_DEL"
controlled_by = [
  "EPLL_DEL",
  "EPLL_TWR",
  "EPWA_S_APP",
  "EPWA_N_APP",
  "EPWA_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPLL_TWR"
controlled_by = [
  "EPLL_TWR",
  "EPWA_S_APP",
  "EPWA_N_APP",
  "EPWA_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPLL_TMA"
controlled_by = [
  "EPLL_TWR",
  "EPWA_S_APP",
  "EPWA_N_APP",
  "EPWA_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPLR"
controlled_by = ["EPLR_R_TWR", "EPWA_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPML"
controlled_by = ["EPML_I_TWR", "EPKK_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPMO_DEL"
controlled_by = [
  "EPMO_DEL",
  "EPMO_TWR",
  "EPWA_N_APP",
  "EPWA_S_APP",
  "EPWA_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPMO_TWR"
controlled_by = [
  "EPMO_TWR",
  "EPWA_N_APP",
  "EPWA_S_APP",
  "EPWA_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPNT"
controlled_by = ["EPNT_R_TWR", "EPKK_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPOD"
controlled_by = ["EPOD_R_TWR", "EPSY_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPPO_DEL"
controlled_by = [
  "EPPO_DEL",
  "EPPO_GND",
  "EPPO_TWR",
  "EPPO_N_APP",
  "EPWW_D_CTR",
  "EPWW_DBT_CTR",
  "EPWW_DT_CTR",
  "EPWW_DTC_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPPO_GND"
controlled_by = [
  "EPPO_GND",
  "EPPO_TWR",
  "EPPO_N_APP",
  "EPWW_D_CTR",
  "EPWW_DBT_CTR",
  "EPWW_DT_CTR",
  "EPWW_DTC_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPPO_TWR"
controlled_by = [
  "EPPO_TWR",
  "EPPO_N_APP",
  "EPWW_D_CTR",
  "EPWW_DBT_CTR",
  "EPWW_DT_CTR",
  "EPWW_DTC_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPPO_TMA_N"
controlled_by = [
  "EPPO_N_APP",
  "EPWW_D_CTR",
  "EPWW_DBT_CTR",
  "EPWW_DT_CTR",
  "EPWW_DTC_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPPO_TMA_S"
controlled_by = [
  "EPPO_S_APP",
  "EPPO_N_APP",
  "EPWW_TM_CTR",
  "EPWW_DT_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_DBT_CTR",
  "EPWW_S_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPPO_FIS"
controlled_by = ["EPPO_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPPZ"
controlled_by = ["EPPZ_R_TWR", "EPSY_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPRA_TWR"
controlled_by = [
  "EPRA_TWR",
  "EPWA_S_APP",
  "EPWA_N_APP",
  "EPWA_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPRA_TMA"
controlled_by = [
  "EPRA_TWR",
  "EPWA_S_APP",
  "EPWA_N_APP",
  "EPWA_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPRZ_GND"
controlled_by = [
  "EPRZ_GND",
  "EPRZ_TWR",
  "EPKK_RZ_APP",
  "EPKK_E_APP",
  "EPKK_APP",
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPRZ_TWR"
controlled_by = [
  "EPRZ_TWR",
  "EPKK_RZ_APP",
  "EPKK_E_APP",
  "EPKK_APP",
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPRZ_TMA"
controlled_by = [
  "EPKK_RZ_APP",
  "EPKK_E_APP",
  "EPKK_APP",
  "EPRZ_TWR",
  "EPWW_J_CTR",
  "EPWW_JR_CTR",
  "EPWW_S_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPSC_TWR"
controlled_by = [
  "EPSC_TWR",
  "EPWW_DBT_CTR",
  "EPWW_DBF_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPSC_TMA"
controlled_by = [
  "EPSC_TWR",
  "EPWW_DBT_CTR",
  "EPWW_DBF_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPSY_TWR"
controlled_by = [
  "EPSY_TWR",
  "EPWW_NE_CTR",
  "EPWW_N_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPSY_TMA"
controlled_by = [
  "EPSY_TWR",
  "EPWW_NE_CTR",
  "EPWW_N_CTR",
  "EPWW_E_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWA_DEL"
controlled_by = [
  "EPWA_DEL",
  "EPWA_GND",
  "EPWA_TWR",
  "EPWA_F_APP",
  "EPWA_APP",
  "EPWA_N_APP",
  "EPWA_S_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWA_GND"
controlled_by = [
  "EPWA_GND",
  "EPWA_TWR",
  "EPWA_F_APP",
  "EPWA_APP",
  "EPWA_N_APP",
  "EPWA_S_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWA_TWR"
controlled_by = [
  "EPWA_TWR",
  "EPWA_F_APP",
  "EPWA_APP",
  "EPWA_N_APP",
  "EPWA_S_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWA_DIR"
controlled_by = [
  "EPWA_F_APP",
  "EPWA_APP",
  "EPWA_S_APP",
  "EPWA_N_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWA_TMA"
controlled_by = [
  "EPWA_APP",
  "EPWA_S_APP",
  "EPWA_N_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWA_TMA_N"
controlled_by = [
  "EPWA_N_APP",
  "EPWA_S_APP",
  "EPWA_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWA_TMA_S"
controlled_by = [
  "EPWA_S_APP",
  "EPWA_N_APP",
  "EPWA_APP",
  "EPWW_C_CTR",
  "EPWW_NE_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_S_CTR",
  "EPWW_E_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWA_FIS_S"
controlled_by = ["EPWA_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPWA_FIS_N"
controlled_by = ["EPSY_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPWR_DEL"
controlled_by = [
  "EPWR_DEL",
  "EPWR_GND",
  "EPWR_TWR",
  "EPPO_S_APP",
  "EPPO_N_APP",
  "EPWW_TM_CTR",
  "EPWW_DT_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_DBT_CTR",
  "EPWW_S_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWR_GND"
controlled_by = [
  "EPWR_GND",
  "EPWR_TWR",
  "EPPO_S_APP",
  "EPPO_N_APP",
  "EPWW_TM_CTR",
  "EPWW_DT_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_DBT_CTR",
  "EPWW_S_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPWR_TWR"
controlled_by = [
  "EPWR_TWR",
  "EPPO_S_APP",
  "EPPO_N_APP",
  "EPWW_TM_CTR",
  "EPWW_DT_CTR",
  "EPWW_TCJ_CTR",
  "EPWW_DTC_CTR",
  "EPWW_DBT_CTR",
  "EPWW_S_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPZG_TWR"
controlled_by = [
  "EPZG_TWR",
  "EPPO_N_APP",
  "EPWW_D_CTR",
  "EPWW_DBT_CTR",
  "EPWW_DT_CTR",
  "EPWW_DTC_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPZG_TMA"
controlled_by = [
  "EPZG_TWR",
  "EPPO_N_APP",
  "EPWW_D_CTR",
  "EPWW_DBT_CTR",
  "EPWW_DT_CTR",
  "EPWW_DTC_CTR",
  "EPWW_N_CTR",
  "EPWW_ALL_CTR",
  "EPWW_ALH_CTR",
]

[[stations]]
id = "EPZP"
controlled_by = ["EPZP_R_TWR", "EPPO_I_APP", "EPWW_I_CTR"]

[[stations]]
id = "EPZR"
controlled_by = ["EPZR_R_TWR", "EPKK_I_APP", "EPWW_I_CTR"]
